# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :unit_test do
    run_tests(
      scheme: "ReferenceiOS",
      only_testing: "ReferenceiOSTests"
    )
  end

  desc "Run UI tests"
  lane :ui_test do
    run_tests(
      scheme: "ReferenceiOSUITests",
      only_testing: "ReferenceiOSUITests"
    )
  end

  lane :test do
    unit_test
    ui_test
  end
end
