name: Pull request check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pr-check:
    name: Check PR against main branch
    runs-on: macos-15-intel

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.6.5"
        bundler: "1.17.2"
        bundler-cache: true
    
    - name: Run Unit tests
      run: bundle exec fastlane test_unit

    - name: Run UI tests
      run: bundle exec fastlane test_ui

    - name: Publish JUnit results
      if: always()
      uses: mikepenz/action-junit-report@v5
      with:
        report_paths: "fastlane/test_output/report.junit"

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: fastlane/test_output/

